version: '3.8'
services:
  web:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./web:/usr/share/nginx/html

  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
